apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ml-app.fullname" . }}
  labels:
    name: {{ include "ml-app.name" . }}
    instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      name: {{ include "ml-app.name" . }}
      instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        name: {{ include "ml-app.name" . }}
        instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.containerPort }}
              protocol: TCP
          env:
            - name: MODEL_URL
              value: "{{ .Values.modelUrl }}"
      dnsPolicy: ClusterFirst
