apiVersion: v1
kind: Service
metadata:
  name: {{ include "survivor-predictor.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "survivor-predictor.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "survivor-predictor.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: {{ .Values.servicePort }}
      targetPort: {{ .Values.containerPort }}
  type: NodePort
