apiVersion: v1
kind: Service
metadata:
  name: {{ include "ml-app.fullname" . }}
  labels:
    name: {{ include "ml-app.name" . }}
    release: {{ .Release.Name }}
spec:
  selector:
    name: {{ include "ml-app.name" . }}
    release: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: {{ .Values.servicePort }}
      targetPort: {{ .Values.containerPort }}
  type: LoadBalancer
